site_name: My Tech Docs
# use_directory_urls: true
site_url: https://srymh.github.io/mdoctag-demo/
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'Teal'
    accent: 'Amber'
  language: 'ja'
  feature:
    tabs: true
plugins:
  - search:
      # separator: '[\s\-]+'
  - mdoctag:
      tagpage_dir: 'tags'
      data_filename: 'tags.json'
